#!/bin/bash

export PATH=$CODE_ROOT:$PATH
export RANDOMS_DIR=$CSCRATCH/norberg/GAMA4/randoms/
:'
python3 gen_gold.py --survey desi --dryrun
python3 gen_gold.py --survey desi

declare -a FIELDS=('R1' 'R2' 'R8' 'R9' 'R10' 'R17')

for FIELD in ${FIELDS[@]}
do
    echo 'Running: '$FIELD

    python3 randoms.py --survey desi --field $FIELD --dryrun
    python3 randoms.py --survey desi --field $FIELD   
done
'
# scp -i ~/.ssh/id_rsa $CSCRATCH/norberg/GAMA4/desi_gold_dryrun.fits $CSCRATCH/norberg/GAMA4/desi_gold.fits $CSCRATCH/norberg/GAMA4/desi_sv3_gold.fits ${1:-1}@login5.cosma.dur.ac.uk:/cosma/home/durham/${1:-1}/data/GAMA4/

scp -i ~/.ssh/id_rsa $RANDOMS_DIR/randoms_R*_0_dryrun.fits $RANDOMS_DIR/randoms_R*_0.fits $RANDOMS_DIR/randoms_R*_x8_0.fits ${1:-1}@login5.cosma.dur.ac.uk:/cosma/home/durham/${1:-1}/data/GAMA4/ 

