# First,
# conda env create -f environment.yml
#
# then define GOLD_DIR and CODE_ROOT in
#
# ~/.conda/envs/lumfn/etc/conda/activate.d/env_vars.sh
#
name: lumfn
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - wget 
  - numpy
  - matplotlib
  - pandas
  - astropy
  - scipy
  - fitsio
  - papermill
  - jupyter
  - notebook>=6.1.5
  - nbformat >=5.0.2
  - coveralls
  - pytest
  - pytest-cov
