#!/bin/bash                                                                                                               
#SBATCH --qos=regular                                                                                                        
#SBATCH --time=120
#SBATCH --nodes=1                                                                                                          
#SBATCH --ntasks-per-node=1                                                                                               
#SBATCH --constraint=haswell                                                                                               
#SBATCH -o gold_pipeline.log                                                                                                

# Submit with:  sbatch gold_pipeline                                                                                        
# to qos of [debug, regular]
#
# See status with e.g. squeue -u mjwilson                                                                                        
#

# Density split LF only. 
export FIELD=G12 

export DRYRUN=''
# export DRYRUN='--dryrun'

export CODE_ROOT=~/desi/BGS/Sam/DESI/

export RANDOMS_DIR=$CSCRATCH/norberg/GAMA4/randoms/
export GOLD_DIR=$CSCRATCH/norberg/GAMA4/

echo
echo 'Environment:'
echo
echo 'Code: '$CODE_ROOT
echo 'Gold output dir.: '$GOLD_DIR
echo 'Randoms output dir: '$RANDOMS_DIR


cd $CODE_ROOT

source /project/projectdirs/desi/software/desi_environment.sh master

echo 'Running gold pipeline'

python gama_gold.py > logs/gama_gold.log

python gen_kEcat.py $DRYRUN > logs/gama_kE.log

python gen_zmax_cat.py $DRYRUN > logs/gama_zmax.log

python ddp_limits.py > logs/ddp_limits.log

python gen_ddp_cat.py $DRYRUN > logs/gama_ddp.log  

# References schechter fn fiven a zmax catalog.
python gen_gold_lf.py $DRYRUN > logs/gama_lumfn.log

python gen_ddp_n8.py --field $FIELD $DRYRUN > logs/gama_ddp_n8_$FIELD.log

# Density dependent schechter fn. given a ddp_n8 catalog.
python gen_gold_lf.py --density_split --field $FIELD $DRYRUN > logs/gama_lumfn_d8_$FIELD.log
