#!/bin/bash
#SBATCH --qos=debug
#SBATCH --time=5
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --constraint=haswell
#SBATCH -o rand_pipeline.log

# Submit with:  sbatch rand_pipeline
# qos [debug, regular]
export FIELD='G12'

export CODE_ROOT=~/desi/BGS/Sam/DESI/
# export CODE_ROOT=~/DESI/

export RANDOMS_DIR=$CSCRATCH/norberg/GAMA4/randoms/
export GOLD_DIR=$CSCRATCH/norberg/GAMA4/

cd $CODE_ROOT

source /project/projectdirs/desi/software/desi_environment.sh master

echo 'Running randoms pipeline for field '$FIELD

# Serial code (--dryrun)
# python randoms.py --field $FIELD --dryrun  > logs/randoms_$FIELD.log

# Uses Pool, should be on interactive. 
python fillfactor.py --field $FIELD --dryrun # > logs/fillfactor_$FIELD.log

# Uses Pool, should be on interactive.
# python bound_dist.py --field $FIELD ## > logs/bound_dist_$FIELD.log

# Assumes python gen_ddp_N8.py has been run. 
# python gen_rand_ddp_N8.py --field $FIELD ## > logs/rand_ddp_N8_$FIELD.log

# pytest

echo 'Done.'
