runtime:
  version: v10
  dryrun: True
  nooverwrite: True
  replay: False
  survey: gama

randoms:
  realz: 0
  prefix: 'randoms_ddp1'
  
lumfn:
  vmax_fillfactor: True  
  selfcount_volfrac: True

comments:
  1st: 'A config. for standard gama run.'