name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04 # ubuntu-latest
    env: 
      USER: HAL
      GOLD_DIR: GAMA4/
      GOLD_LOGS: GAMA4/logs/
      RANDOMS_DIR: GAMA4/randoms/
      RANDOMS_LOGS: GAMA4/randoms/logs/

    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        mkdir -p $GOLD_LOGS
        mkdir -p $RANDOMS_LOGS

        conda install pytest
        
        # pytest -rP
        pytest -x --disable-warnings
